apiVersion: v1
kind: Service
metadata:
  name: connector-service
spec:
  type: ClusterIP
  selector:
    component: connector
  ports:
    - port: 5000
      name: http
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connector-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: connector
  template:
    metadata:
      labels:
        component: connector
    spec:
      containers:
        - name: connector
          image: ghcr.io/desmond766/connector:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
          command: ["gunicorn"]
          args: ["-b", "0.0.0.0:5000", "--timeout", "30", "--workers", "1", "app:app"]
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "cockroachdb-public"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP