apiVersion: batch/v1
kind: Job
metadata:
  name: database-init
  labels:
    app: cockroachdb
spec:
  template:
    spec:
      containers:
      - name: database-init
        image: ghcr.io/desmond766/db-init:latest
        imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure
